#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceWebHook
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ReadMeter")]
	public partial class ModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertZl_User_Follow(Zl_User_Follow instance);
    partial void UpdateZl_User_Follow(Zl_User_Follow instance);
    partial void DeleteZl_User_Follow(Zl_User_Follow instance);
    partial void Insertt_Consumer(t_Consumer instance);
    partial void Updatet_Consumer(t_Consumer instance);
    partial void Deletet_Consumer(t_Consumer instance);
    #endregion
		
		public ModelDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ReadMeterConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Zl_User_Follow> Zl_User_Follows
		{
			get
			{
				return this.GetTable<Zl_User_Follow>();
			}
		}
		
		public System.Data.Linq.Table<t_Consumer> t_Consumers
		{
			get
			{
				return this.GetTable<t_Consumer>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Zl_User_Follow")]
	public partial class Zl_User_Follow : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdFollower;
		
		private System.Nullable<bool> _IsFollower;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdFollowerChanging(string value);
    partial void OnIdFollowerChanged();
    partial void OnIsFollowerChanging(System.Nullable<bool> value);
    partial void OnIsFollowerChanged();
    #endregion
		
		public Zl_User_Follow()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdFollower", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdFollower
		{
			get
			{
				return this._IdFollower;
			}
			set
			{
				if ((this._IdFollower != value))
				{
					this.OnIdFollowerChanging(value);
					this.SendPropertyChanging();
					this._IdFollower = value;
					this.SendPropertyChanged("IdFollower");
					this.OnIdFollowerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsFollower", DbType="Bit")]
		public System.Nullable<bool> IsFollower
		{
			get
			{
				return this._IsFollower;
			}
			set
			{
				if ((this._IsFollower != value))
				{
					this.OnIsFollowerChanging(value);
					this.SendPropertyChanging();
					this._IsFollower = value;
					this.SendPropertyChanged("IsFollower");
					this.OnIsFollowerChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_Consumers")]
	public partial class t_Consumer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ConsumerId;
		
		private System.Nullable<byte> _Zoom;
		
		private string _Description;
		
		private System.Nullable<int> _SetDefault;
		
		private string _Acronym;
		
		private string _Address;
		
		private string _Email;
		
		private string _Fax;
		
		private string _Phone;
		
		private string _Contact;
		
		private string _Career;
		
		private string _DMA;
		
		private long _Id;
		
		private string _ZaloId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnConsumerIdChanging(string value);
    partial void OnConsumerIdChanged();
    partial void OnZoomChanging(System.Nullable<byte> value);
    partial void OnZoomChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnSetDefaultChanging(System.Nullable<int> value);
    partial void OnSetDefaultChanged();
    partial void OnAcronymChanging(string value);
    partial void OnAcronymChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnFaxChanging(string value);
    partial void OnFaxChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnContactChanging(string value);
    partial void OnContactChanged();
    partial void OnCareerChanging(string value);
    partial void OnCareerChanged();
    partial void OnDMAChanging(string value);
    partial void OnDMAChanged();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnZaloIdChanging(string value);
    partial void OnZaloIdChanged();
    #endregion
		
		public t_Consumer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConsumerId", DbType="VarChar(50)")]
		public string ConsumerId
		{
			get
			{
				return this._ConsumerId;
			}
			set
			{
				if ((this._ConsumerId != value))
				{
					this.OnConsumerIdChanging(value);
					this.SendPropertyChanging();
					this._ConsumerId = value;
					this.SendPropertyChanged("ConsumerId");
					this.OnConsumerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zoom", DbType="TinyInt")]
		public System.Nullable<byte> Zoom
		{
			get
			{
				return this._Zoom;
			}
			set
			{
				if ((this._Zoom != value))
				{
					this.OnZoomChanging(value);
					this.SendPropertyChanging();
					this._Zoom = value;
					this.SendPropertyChanged("Zoom");
					this.OnZoomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(4000)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SetDefault", DbType="Int")]
		public System.Nullable<int> SetDefault
		{
			get
			{
				return this._SetDefault;
			}
			set
			{
				if ((this._SetDefault != value))
				{
					this.OnSetDefaultChanging(value);
					this.SendPropertyChanging();
					this._SetDefault = value;
					this.SendPropertyChanged("SetDefault");
					this.OnSetDefaultChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Acronym", DbType="NVarChar(50)")]
		public string Acronym
		{
			get
			{
				return this._Acronym;
			}
			set
			{
				if ((this._Acronym != value))
				{
					this.OnAcronymChanging(value);
					this.SendPropertyChanging();
					this._Acronym = value;
					this.SendPropertyChanged("Acronym");
					this.OnAcronymChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(500)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="NChar(20)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this.OnFaxChanging(value);
					this.SendPropertyChanging();
					this._Fax = value;
					this.SendPropertyChanged("Fax");
					this.OnFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NChar(20)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contact", DbType="NVarChar(250)")]
		public string Contact
		{
			get
			{
				return this._Contact;
			}
			set
			{
				if ((this._Contact != value))
				{
					this.OnContactChanging(value);
					this.SendPropertyChanging();
					this._Contact = value;
					this.SendPropertyChanged("Contact");
					this.OnContactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Career", DbType="NVarChar(250)")]
		public string Career
		{
			get
			{
				return this._Career;
			}
			set
			{
				if ((this._Career != value))
				{
					this.OnCareerChanging(value);
					this.SendPropertyChanging();
					this._Career = value;
					this.SendPropertyChanged("Career");
					this.OnCareerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DMA", DbType="NVarChar(50)")]
		public string DMA
		{
			get
			{
				return this._DMA;
			}
			set
			{
				if ((this._DMA != value))
				{
					this.OnDMAChanging(value);
					this.SendPropertyChanging();
					this._DMA = value;
					this.SendPropertyChanged("DMA");
					this.OnDMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZaloId", DbType="NVarChar(100)")]
		public string ZaloId
		{
			get
			{
				return this._ZaloId;
			}
			set
			{
				if ((this._ZaloId != value))
				{
					this.OnZaloIdChanging(value);
					this.SendPropertyChanging();
					this._ZaloId = value;
					this.SendPropertyChanged("ZaloId");
					this.OnZaloIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
